Outlines
- introduction to tensors
- getting information from tensors
- manipulating tensors
- tensors and numpy
- using @tf.function
- using GPUs with tensorflow
- exercises

# Introduction to Tensors

In [5]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [6]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [9]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [10]:
# check the number of dimensions of a vector
vector.ndim

1

In [11]:
# create a matrix (has more than 1 dimenson)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [12]:
# check the number of dimensions of a matrix
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16) # specify the data type with dtype parameter, without ie -> dtype=float32
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [15]:
# the number of dimensiond of another_matrix
another_matrix.ndim

2

In [16]:
# create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [17]:
tensor.ndim

3

* scalar: a song number
* vector: a number with directions (e.g. wind speed with direction)
* matrix: a 2-dimensional array of numbers
* tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)